//go:build ignore

// Command render converts the live agent command envelope into checked-in skill references.
package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type envelope struct {
	OK   bool `json:"ok"`
	Data struct {
		Commands []command `json:"commands"`
	} `json:"data"`
}

type command struct {
	Name          string           `json:"name"`
	Path          string           `json:"path"`
	Use           string           `json:"use"`
	Short         string           `json:"short"`
	Long          string           `json:"long,omitempty"`
	Aliases       []string         `json:"aliases"`
	Runnable      bool             `json:"runnable"`
	Flags         []flag           `json:"flags"`
	Subcommands   []commandSummary `json:"subcommands"`
	ReadOnly      bool             `json:"read_only"`
	RequiresInput bool             `json:"requires_input"`
}

type commandSummary struct {
	Name     string `json:"name"`
	Path     string `json:"path"`
	Short    string `json:"short"`
	Runnable bool   `json:"runnable"`
}

type flag struct {
	Name      string `json:"name"`
	Shorthand string `json:"shorthand,omitempty"`
	Type      string `json:"type"`
	Default   string `json:"default"`
	Usage     string `json:"usage"`
	Required  bool   `json:"required"`
	Inherited bool   `json:"inherited"`
}

func main() {
	if len(os.Args) != 7 {
		fatalf("usage: render INPUT_JSON OUTPUT_JSON OUTPUT_MARKDOWN SKILL_ROOT OUTPUT_INTEGRITY OUTPUT_GO")
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		fatalf("read command envelope: %v", err)
	}
	var source envelope
	if err := json.Unmarshal(raw, &source); err != nil || !source.OK {
		fatalf("decode successful command envelope: %v", err)
	}
	sort.Slice(source.Data.Commands, func(i, j int) bool { return source.Data.Commands[i].Path < source.Data.Commands[j].Path })

	manifest, err := json.MarshalIndent(struct {
		Commands []command `json:"commands"`
	}{Commands: source.Data.Commands}, "", "  ")
	if err != nil {
		fatalf("encode command manifest: %v", err)
	}
	manifest = append(manifest, '\n')
	if err := os.WriteFile(os.Args[2], manifest, 0o644); err != nil {
		fatalf("write command manifest: %v", err)
	}

	var markdown strings.Builder
	markdown.WriteString("# Daiku command reference\n\nGenerated from `daiku commands --agent`; do not edit by hand. Live introspection wins if this reference differs.\n\n")
	for _, item := range source.Data.Commands {
		if !item.Runnable {
			continue
		}
		fmt.Fprintf(&markdown, "## `%s`\n\n%s\n\nUsage: `%s`\n", item.Path, item.Short, item.Use)
		local := make([]flag, 0)
		for _, value := range item.Flags {
			if !value.Inherited && value.Name != "help" {
				local = append(local, value)
			}
		}
		if len(local) > 0 {
			markdown.WriteString("\nFlags:\n\n")
			for _, value := range local {
				required := ""
				if value.Required {
					required = " (required)"
				}
				fmt.Fprintf(&markdown, "- `--%s` (%s)%s: %s\n", value.Name, value.Type, required, value.Usage)
			}
		}
		markdown.WriteByte('\n')
	}
	reference := strings.TrimRight(markdown.String(), "\n") + "\n"
	if err := os.WriteFile(os.Args[3], []byte(reference), 0o644); err != nil {
		fatalf("write command reference: %v", err)
	}

	paths := []string{
		"SKILL.md",
		"agents/openai.yaml",
		"references/commands.json",
		"references/commands.md",
		"references/safety.md",
		"references/workflows.md",
	}
	digests := make(map[string]string, len(paths))
	for _, path := range paths {
		var sourcePath string
		switch path {
		case "references/commands.json":
			sourcePath = os.Args[2]
		case "references/commands.md":
			sourcePath = os.Args[3]
		default:
			sourcePath = filepath.Join(os.Args[4], filepath.FromSlash(path))
		}
		content, err := os.ReadFile(sourcePath)
		if err != nil {
			fatalf("read integrity input %s: %v", path, err)
		}
		digests[path] = fmt.Sprintf("%x", sha256.Sum256(content))
	}
	integrity, err := json.MarshalIndent(struct {
		Version int               `json:"version"`
		Files   map[string]string `json:"files"`
	}{Version: 1, Files: digests}, "", "  ")
	if err != nil {
		fatalf("encode integrity manifest: %v", err)
	}
	if err := os.WriteFile(os.Args[5], append(integrity, '\n'), 0o644); err != nil {
		fatalf("write integrity manifest: %v", err)
	}
	var generated strings.Builder
	generated.WriteString("// Code generated by scripts/skill/generate.sh; DO NOT EDIT.\npackage skillmeta\n\nvar Digests = map[string]string{\n")
	for _, path := range paths {
		fmt.Fprintf(&generated, "\t%q: %q,\n", path, digests[path])
	}
	generated.WriteString("}\n")
	formatted, err := format.Source([]byte(generated.String()))
	if err != nil {
		fatalf("format compiled integrity metadata: %v", err)
	}
	if err := os.WriteFile(os.Args[6], formatted, 0o644); err != nil {
		fatalf("write compiled integrity metadata: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "skill reference generator: "+format+"\n", args...)
	os.Exit(1)
}
